name: Windows C++ Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # 配置 MSVC 编译器
      - name: Initialize MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      # 编译所有文件
      - name: Compile Main.cpp & clHCA.cpp
        run: cl /EHsc Main.cpp clHCA.cpp

      # 上传 EXE 到 Artifacts
      - name: Upload EXE
        uses: actions/upload-artifact@v7
        with:
          name: Windows-EXE
          path: Main.exe
          if-no-files-found: error
